"""reply post

Revision ID: 029cf5b5b54a
Revises: 6f4c8aaeeb34
Create Date: 2021-11-08 20:12:13.513906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029cf5b5b54a'
down_revision = '6f4c8aaeeb34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'post', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'parent_id')
    # ### end Alembic commands ###
