"""new fields(about_me, last_seen) in user model

Revision ID: 79502749bada
Revises: edecbbbdf838
Create Date: 2021-11-04 16:43:52.547200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79502749bada'
down_revision = 'edecbbbdf838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
